# Generated by Django 5.2.7 on 2025-11-22 18:56

import visitas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0005_alter_visita_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[visitas.validators.validar_rut]),
        ),
    ]
