# Generated by Django 5.2.7 on 2025-12-13 20:04

import visitas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0008_alter_visita_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='nombre',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='visita',
            old_name='fecha_de_visita',
            new_name='fecha_visita',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='motivo',
        ),
        migrations.AddField(
            model_name='visita',
            name='servicio',
            field=models.CharField(default='Servicio general', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.CharField(max_length=12, validators=[visitas.validators.validar_rut]),
        ),
    ]
