# Generated by Django 5.2.7 on 2025-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0009_rename_nombre_visita_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='servicio',
            field=models.CharField(choices=[('corte', 'Corte de cabello'), ('tintura', 'Tintura'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('alisado', 'Alisado'), ('peinado', 'Peinado')], max_length=50),
        ),
    ]
