# Generated by Django 5.2.7 on 2025-12-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0010_alter_visita_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visita',
            name='servicio',
            field=models.CharField(choices=[('corte', 'Corte de cabello'), ('tintura', 'Tintura'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('alisado', 'Alisado'), ('peinado', 'Peinado'), ('prefilado de cejas', 'Perfilado de Cejas'), ('lifting de pestañas', 'Lifting de Pestañas')], max_length=50),
        ),
    ]
