# Generated by Django 5.2.7 on 2025-12-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0012_alter_visita_fecha_visita_alter_visita_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='servicio',
            field=models.CharField(choices=[('corte', 'Corte de cabello'), ('tintura', 'Tintura'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('alisado', 'Alisado'), ('peinado', 'Peinado'), ('perfilado de cejas', 'Perfilado de cejas'), ('lifting de pestañas', 'Lifting de pestañas')], max_length=50),
        ),
    ]
